#modified from @sixeyed 
FROM alpine:latest

ARG DNSMASQ_VERSION="2.80-r3"

RUN apk add --no-cache dnsmasq=$DNSMASQ_VERSION

EXPOSE 53/udp

ENTRYPOINT ["dnsmasq"]
CMD ["--keep-in-foreground", "--log-facility=-"]

COPY dnsmasq.conf /etc/dnsmasq.conf
